### ISSUE TITLE
Find missing tracks due to conversion

### ISSUE THREAD

**Issue by elijahr** [rshea0/tuneup-prime#51]
I am writing a script that recursively converts lossless audio files to WAV and lossy audio files to MP3. The filename and tags within the file remain intact. The original file is deleted. Engine Prime will see this as a missing file. For tuneup-prime to find missing audio files, it looks for the same file name I think, right? It would be great if it could match on other criteria such as ID3 tag info, track length, audio fingerprint - or at the very least, same file name with any audio extension.

**Comment by rshea0** [comment]
This is already a planned feature. Tracking it here: #6.

I'm on a bit of a mental health break right now, but I hope to be back to providing updates within a month.
