### ISSUE TITLE
Playlists without folders are moved to the root folder

### ISSUE THREAD

**Issue by Houseman-HH** [rshea0/tuneup-prime#72]
### Issue description
Since the latest update, I can no longer move my smart lists into subfolders.

With each new analysis they are moved back to the main directory.

This is very annoying and messed up my whole folder structure.

Please fix this bug quickly!

thank you

### Environment

- `tuneup PRIME` version: *2.30
- Engine PRIME version: 2.10
- Operating System: Mac Montery

**Comment by rshea0** [comment]
*Mirroring my reply from the forum*

This is an unintended side effect of adding the folders feature. Your folder structure should be replicated in the config file, otherwise playlists without a folder will be moved to the root.

One way I could possibly handle this is if a config doesn’t contain any folders, existing playlists won’t be re-parented and will remain where they are.

**Comment by Houseman-HH** [comment]
I find that very sad.

Carrying out my engine folder structure with the command lines in the configuration file is cumbersome and time-consuming.

The creation of folder structures is much faster and more comfortable in Engine.

I think this version is more of a step backwards than a step forward.

Maybe they can fix that.

I'm back to 2.20

Best regards

Holger

**Comment by rshea0** [comment]
I'll get a patch update out later today that allows playlists at the root stay in whatever folder you've placed them in within Engine so your workflow is still possible.

**Comment by Houseman-HH** [comment]
Great support :)

**Comment by Houseman-HH** [comment]
Hey
I noticed something else:

If, for example, I subsequently change a tag such as comment or rating in a smartlist that has already been created, the title remains in the wrong list with the new changes.

I then have to manually delete the changed titles from the list.

After deleting and re-creating the list, the assignment is correct.

Maybe you can test it - I noticed it by accident

thank you

**Comment by rshea0** [comment]
Are you changing the tag from within Engine, or from the file?

Currently the app only uses Engine's tags to build the smart playlists so if you've edited the file's tag but haven't refreshed those changes within Engine, Tuneup won't see it.

One of the next features I'm adding is the ability to use the file tags (including custom ID3 tags) for smart playlists.

**Comment by Houseman-HH** [comment]
Only Engine tags will be modified

**Comment by rshea0** [comment]
Interesting, so you're saying you've modified the tag via Engine, but the smart playlists don't take those changes into account?

Could you please open a new bug and post a reproduction example with the song/tags in question and the smart playlist config you're using?

**Comment by Houseman-HH** [comment]
Correct- bug is opened

**Comment by Houseman-HH** [comment]
For explanation:
It only affects tracks that were previously in the smartlist!

New tracks that are being added to a lsite for the first time are flawless and the list is correct.
But as soon as I change a track in an existing list, the error occurs.
